package view; // Package name for the class

import classes.DataValidation; // Import DataValidation class for validating data
import classes.ExpenseManager; // Import ExpenseManager class for managing expenses
import classes.Expense; // Import Expense class for expense data handling
import java.awt.Desktop;
import java.net.URI;
import java.time.LocalDate; // Import LocalDate class for handling dates
import java.time.ZoneId; // Import ZoneId class for handling time zones
import javax.swing.DefaultComboBoxModel; // Import DefaultComboBoxModel for combo box data model
import javax.swing.JOptionPane; // Import JOptionPane for displaying dialogs

/**
 * AddExpenseScreen class extends JFrame to create a form for adding expenses.
 * This class provides a graphical user interface to input and manage expense details.
 * 
 * @author Liron
 */
public class AddExpenseScreen extends javax.swing.JFrame {

    /**
     * Creates new form AddExpenseScreen
     * Initializes the components of the form and sets up the combo box with predefined expense categories.
     */
    public AddExpenseScreen() {
        initComponents(); // Initialize the form's components
        
        // Define a list of expense categories to be displayed in the combo box
        String[] columnDetails = {
            "Utilities (Electricity)", "Utilities (Water)", "Internet",
            "Maintenance/Repairs", "Insurance", "Property Taxes", "HOA Fees",
            "Cleaning Services", "Security Deposit", "Cable TV", "Parking Fees",
            "Pet Fees", "Trash Removal", "Furniture Rental", "Moving Expenses",
            "Legal Fees", "Key Replacement", "Pet Damage Repair", "Miscellaneous"
        };
        
        // Set the model of the combo box with the predefined expense categories
        cmbDetails.setModel(new DefaultComboBoxModel<>(columnDetails));
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack1 = new swing.CustomButtonGradient();
        lblHeading = new javax.swing.JLabel();
        Mailbtn = new javax.swing.JButton();
        ytubebtn = new javax.swing.JButton();
        jLabel_inven2 = new javax.swing.JLabel();
        btnMinamise = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblType = new javax.swing.JLabel();
        cmbDetails = new javax.swing.JComboBox<>();
        lblType1 = new javax.swing.JLabel();
        caldate = new com.toedter.calendar.JCalendar();
        lblinvoiceno = new javax.swing.JLabel();
        txtinvoiceno = new javax.swing.JTextField();
        lblCompany = new javax.swing.JLabel();
        txtCompany = new javax.swing.JTextField();
        lblDOB = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        btnAdd = new swing.CustomButtonGradient();
        lblErrorInvoice = new javax.swing.JLabel();
        lblErrorCompany = new javax.swing.JLabel();
        lblErrorAmount = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblErrorPaymentDate = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(21, 25, 28));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(21, 25, 28));

        btnBack1.setForeground(new java.awt.Color(0, 0, 0));
        btnBack1.setText("Back");
        btnBack1.setColor1(new java.awt.Color(15, 214, 79));
        btnBack1.setColor2(new java.awt.Color(248, 239, 66));
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        lblHeading.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lblHeading.setForeground(new java.awt.Color(169, 224, 49));
        lblHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeading.setText("ADD Expense");
        lblHeading.setMaximumSize(new java.awt.Dimension(257, 42));
        lblHeading.setMinimumSize(new java.awt.Dimension(257, 42));

        Mailbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Secured_Letter_32px.png"))); // NOI18N
        Mailbtn.setToolTipText("Email");
        Mailbtn.setBorder(null);
        Mailbtn.setBorderPainted(false);
        Mailbtn.setContentAreaFilled(false);
        Mailbtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Secured_Letter_32px_2.png"))); // NOI18N

        ytubebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_YouTube_32px.png"))); // NOI18N
        ytubebtn.setToolTipText("YouTube");
        ytubebtn.setBorder(null);
        ytubebtn.setBorderPainted(false);
        ytubebtn.setContentAreaFilled(false);
        ytubebtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_YouTube_32px_1.png"))); // NOI18N
        ytubebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ytubebtnActionPerformed(evt);
            }
        });

        jLabel_inven2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel_inven2.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven2.setText("support         Help");

        btnMinamise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Minus_32px_1.png"))); // NOI18N
        btnMinamise.setToolTipText("Minimize");
        btnMinamise.setBorder(null);
        btnMinamise.setBorderPainted(false);
        btnMinamise.setContentAreaFilled(false);
        btnMinamise.setFocusPainted(false);
        btnMinamise.setRequestFocusEnabled(false);
        btnMinamise.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Minus_30px_3.png"))); // NOI18N
        btnMinamise.setVerifyInputWhenFocusTarget(false);
        btnMinamise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinamiseMouseClicked(evt);
            }
        });

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_32px.png"))); // NOI18N
        btnExit.setToolTipText("Close");
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setRequestFocusEnabled(false);
        btnExit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_30px_3.png"))); // NOI18N
        btnExit.setVerifyInputWhenFocusTarget(false);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitclicked(evt);
            }
        });

        lblType.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblType.setForeground(new java.awt.Color(169, 224, 49));
        lblType.setText("Details:");

        cmbDetails.setBackground(new java.awt.Color(21, 25, 28));
        cmbDetails.setForeground(new java.awt.Color(169, 224, 49));
        cmbDetails.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbDetails.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(169, 224, 49)));
        cmbDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmbDetails.setOpaque(true);

        lblType1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblType1.setForeground(new java.awt.Color(169, 224, 49));
        lblType1.setText("Date:");

        lblinvoiceno.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblinvoiceno.setForeground(new java.awt.Color(169, 224, 49));
        lblinvoiceno.setText("invoice no:");

        txtinvoiceno.setBackground(new java.awt.Color(31, 36, 42));
        txtinvoiceno.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txtinvoiceno.setForeground(new java.awt.Color(255, 255, 255));
        txtinvoiceno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));

        lblCompany.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblCompany.setForeground(new java.awt.Color(169, 224, 49));
        lblCompany.setText("Company:");

        txtCompany.setBackground(new java.awt.Color(31, 36, 42));
        txtCompany.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txtCompany.setForeground(new java.awt.Color(255, 255, 255));
        txtCompany.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));

        lblDOB.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblDOB.setForeground(new java.awt.Color(169, 224, 49));
        lblDOB.setText("Amount:");

        txtAmount.setBackground(new java.awt.Color(31, 36, 42));
        txtAmount.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txtAmount.setForeground(new java.awt.Color(255, 255, 255));
        txtAmount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));

        btnAdd.setForeground(new java.awt.Color(0, 0, 0));
        btnAdd.setText("Add Expense");
        btnAdd.setColor1(new java.awt.Color(169, 224, 49));
        btnAdd.setColor2(new java.awt.Color(169, 224, 49));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblErrorInvoice.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblErrorInvoice.setForeground(new java.awt.Color(244, 67, 54));
        lblErrorInvoice.setText("*");

        lblErrorCompany.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblErrorCompany.setForeground(new java.awt.Color(244, 67, 54));
        lblErrorCompany.setText("*");

        lblErrorAmount.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblErrorAmount.setForeground(new java.awt.Color(244, 67, 54));
        lblErrorAmount.setText("*");

        jScrollPane1.setBorder(null);

        lblErrorPaymentDate.setBackground(new java.awt.Color(21, 25, 28));
        lblErrorPaymentDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 25, 28)));
        lblErrorPaymentDate.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lblErrorPaymentDate.setForeground(new java.awt.Color(244, 67, 54));
        jScrollPane1.setViewportView(lblErrorPaymentDate);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Mailbtn)
                                .addGap(40, 40, 40)
                                .addComponent(ytubebtn))
                            .addComponent(jLabel_inven2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(btnMinamise, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblType1)
                            .addComponent(lblType)
                            .addComponent(lblinvoiceno)
                            .addComponent(lblCompany)
                            .addComponent(lblDOB))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblErrorAmount)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtinvoiceno, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblErrorInvoice))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblErrorCompany))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(caldate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMinamise, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Mailbtn)
                            .addComponent(ytubebtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_inven2))
                    .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblType)
                    .addComponent(cmbDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblType1)
                    .addComponent(caldate, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtinvoiceno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblinvoiceno)
                            .addComponent(lblErrorInvoice))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCompany)
                            .addComponent(lblErrorCompany))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDOB)
                            .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblErrorAmount))
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // Return to the ExpenseScreen when the "Back" button is clicked
        new ExpenseScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnMinamiseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinamiseMouseClicked
       // minimise the aplication
        this.setState(ICONIFIED);
    }//GEN-LAST:event_btnMinamiseMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // Get user input
        String details = (String) cmbDetails.getSelectedItem(); // Get the selected item from the combDetails JComboBox
        String invoiceNo = txtinvoiceno.getText();      // get the value entered in the surname field
        String AmountText = txtAmount.getText();        // get the value enterd in the amount field
        double Amount;
        try {
            // Clean the AmountText by removing currency symbols and commas
            AmountText = AmountText.replaceAll("[^\\d.]", "");

            // Parse the cleaned AmountText to a double
            Amount = Double.parseDouble(AmountText);
        } catch (NumberFormatException e) {
            lblErrorAmount.setText("Amount must be a valid number.");
            return;
        }

        String company = txtCompany.getText();          // get the value entered in the email field
        LocalDate paymentdate = caldate.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        // Data Validation
        DataValidation valid = new DataValidation();           // create a new DataValidation object to validate the user input
        lblErrorPaymentDate.setText(valid.checkPaymentDate(paymentdate)); // check if the payment date input is valid and set the error message if not
        lblErrorCompany.setText(valid.checkCompany(company));   // check if the firstname input is valid and set the error message if not
        lblErrorAmount.setText(valid.checkAmount(AmountText));         // check if the Amount input is valid and set the error message if not
        lblErrorInvoice.setText(valid.checkInvoice(invoiceNo));         // check if the Invoice input is valid and set the error message if not
    
        // Check if Expense already exists
        if (valid.isValid()) {
            if (valid.expenseExists(company, 0)) {
                // Display an error message if the owner with the given email already exists
                JOptionPane.showMessageDialog(null, "Expense already exists.");
                return;
            } else {
                if (valid.isValid()) {
                    // Convert AmountText to double after validation

                }
                // Create a new Owner object and add it to the database
                Expense expense = new Expense(paymentdate, details, invoiceNo, company, Amount);
                ExpenseManager em = new ExpenseManager();
                em.addExpense(expense);
                JOptionPane.showMessageDialog(null, "Expense has been added");   // Display a message to the user that the owner has been successfully added

                // Close the add owner screen and open the owner screen
                new ExpenseScreen().setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnExitclicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitclicked
        // exit the application
         System.exit(0);
    }//GEN-LAST:event_btnExitclicked

    private void ytubebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ytubebtnActionPerformed
      try {
            String url = "https://vimeo.com/994576038#t=2m51s.";
            // Use Desktop class to open the URL
            if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)) {
                Desktop.getDesktop().browse(new URI(url));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_ytubebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddExpenseScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddExpenseScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddExpenseScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddExpenseScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddExpenseScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Mailbtn;
    private swing.CustomButtonGradient btnAdd;
    private swing.CustomButtonGradient btnBack1;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnMinamise;
    private com.toedter.calendar.JCalendar caldate;
    private javax.swing.JComboBox<String> cmbDetails;
    private javax.swing.JLabel jLabel_inven2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCompany;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblErrorAmount;
    private javax.swing.JLabel lblErrorCompany;
    private javax.swing.JLabel lblErrorInvoice;
    private javax.swing.JTextPane lblErrorPaymentDate;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel lblType1;
    private javax.swing.JLabel lblinvoiceno;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtCompany;
    private javax.swing.JTextField txtinvoiceno;
    private javax.swing.JButton ytubebtn;
    // End of variables declaration//GEN-END:variables
}