package view; // Package declaration for organizing the class within the 'view' package

// Import custom classes for data validation, payment management, payment representation, and tenant management
import classes.DataValidation; // Custom class for validating data inputs
import classes.PaymentManager;  // Custom class for managing payment operations
import classes.Payment;         // Custom class representing a payment entity
import classes.TenantManager;   // Custom class for managing tenant-related operations
import java.awt.Desktop;
import java.net.URI;

// Import Java standard library classes for handling dates and time zones
import java.time.LocalDate;     // Standard class for representing dates (year, month, day)
import java.time.ZoneId;        // Standard class for representing time zones

// Import Swing classes for GUI components
import javax.swing.DefaultComboBoxModel; // Swing class for handling the data model of combo boxes
import javax.swing.JOptionPane;          // Swing class for displaying standard dialog boxes (message, input, confirmation)

/**
 *
 * @author Liron
 */
public class AddPaymentScreen extends javax.swing.JFrame {
    
     // Declare a PaymentManager instance for managing payment operations
    private PaymentManager paymentManager;

    // Declare a TenantManager instance for managing tenant operations
    private TenantManager tenantManager;

    public AddPaymentScreen() {
        initComponents(); // Initialize GUI components
        tenantManager = new TenantManager(); // Instantiate TenantManager
        paymentManager = new PaymentManager(); // Instantiate PaymentManager
        populateComboBox(); // Populate the combo box with tenant names
    }


     private void populateComboBox() {
        // Get tenant names from PaymentManager
        java.util.ArrayList<String> tenantNames = paymentManager.getTenantNames();
        // Set the model for the combo box with the list of tenant names
        cmbTenant.setModel(new DefaultComboBoxModel<>(tenantNames.toArray(new String[0])));
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack1 = new swing.CustomButtonGradient();
        lblHeading = new javax.swing.JLabel();
        Mailbtn = new javax.swing.JButton();
        ytubebtn = new javax.swing.JButton();
        jLabel_inven2 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        lblType = new javax.swing.JLabel();
        cmbTenant = new javax.swing.JComboBox<>();
        lblType1 = new javax.swing.JLabel();
        calDateCreated = new com.toedter.calendar.JCalendar();
        lblinvoiceno = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        lblCompany = new javax.swing.JLabel();
        txtInvoiceNo = new javax.swing.JTextField();
        btnAdd = new swing.CustomButtonGradient();
        lblErrorInvoice = new javax.swing.JLabel();
        lblErrorAmount = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblErrorDatePaid = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(21, 25, 28));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(21, 25, 28));

        btnBack1.setForeground(new java.awt.Color(0, 0, 0));
        btnBack1.setText("Back");
        btnBack1.setColor1(new java.awt.Color(15, 214, 79));
        btnBack1.setColor2(new java.awt.Color(248, 239, 66));
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        lblHeading.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lblHeading.setForeground(new java.awt.Color(169, 224, 49));
        lblHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeading.setText("ADD Payment");
        lblHeading.setMaximumSize(new java.awt.Dimension(257, 42));
        lblHeading.setMinimumSize(new java.awt.Dimension(257, 42));

        Mailbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Secured_Letter_32px.png"))); // NOI18N
        Mailbtn.setToolTipText("Email");
        Mailbtn.setBorder(null);
        Mailbtn.setBorderPainted(false);
        Mailbtn.setContentAreaFilled(false);
        Mailbtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Secured_Letter_32px_2.png"))); // NOI18N

        ytubebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_YouTube_32px.png"))); // NOI18N
        ytubebtn.setToolTipText("YouTube");
        ytubebtn.setBorder(null);
        ytubebtn.setBorderPainted(false);
        ytubebtn.setContentAreaFilled(false);
        ytubebtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_YouTube_32px_1.png"))); // NOI18N
        ytubebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ytubebtnActionPerformed(evt);
            }
        });

        jLabel_inven2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel_inven2.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven2.setText("support         Help");

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Minus_32px_1.png"))); // NOI18N
        jButton11.setToolTipText("Minimize");
        jButton11.setBorder(null);
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setFocusPainted(false);
        jButton11.setRequestFocusEnabled(false);
        jButton11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Minus_30px_3.png"))); // NOI18N
        jButton11.setVerifyInputWhenFocusTarget(false);
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_32px.png"))); // NOI18N
        jButton10.setToolTipText("Close");
        jButton10.setBorder(null);
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setRequestFocusEnabled(false);
        jButton10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_30px_3.png"))); // NOI18N
        jButton10.setVerifyInputWhenFocusTarget(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        lblType.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblType.setForeground(new java.awt.Color(169, 224, 49));
        lblType.setText("Tenant:");

        cmbTenant.setBackground(new java.awt.Color(21, 25, 28));
        cmbTenant.setForeground(new java.awt.Color(169, 224, 49));
        cmbTenant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  "1", "2","3","4" }));
        cmbTenant.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(169, 224, 49)));
        cmbTenant.setOpaque(true);

        lblType1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblType1.setForeground(new java.awt.Color(169, 224, 49));
        lblType1.setText("Date Paid:");

        lblinvoiceno.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblinvoiceno.setForeground(new java.awt.Color(169, 224, 49));
        lblinvoiceno.setText("Amount:");

        txtAmount.setBackground(new java.awt.Color(31, 36, 42));
        txtAmount.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txtAmount.setForeground(new java.awt.Color(255, 255, 255));
        txtAmount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));

        lblCompany.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblCompany.setForeground(new java.awt.Color(169, 224, 49));
        lblCompany.setText("Invoice:");

        txtInvoiceNo.setBackground(new java.awt.Color(31, 36, 42));
        txtInvoiceNo.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txtInvoiceNo.setForeground(new java.awt.Color(255, 255, 255));
        txtInvoiceNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));

        btnAdd.setForeground(new java.awt.Color(0, 0, 0));
        btnAdd.setText("Add Payment");
        btnAdd.setColor1(new java.awt.Color(169, 224, 49));
        btnAdd.setColor2(new java.awt.Color(169, 224, 49));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblErrorInvoice.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblErrorInvoice.setForeground(new java.awt.Color(244, 67, 54));
        lblErrorInvoice.setText("*");

        lblErrorAmount.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblErrorAmount.setForeground(new java.awt.Color(244, 67, 54));
        lblErrorAmount.setText("*");

        jScrollPane1.setBorder(null);

        lblErrorDatePaid.setBackground(new java.awt.Color(21, 25, 28));
        lblErrorDatePaid.setBorder(null);
        lblErrorDatePaid.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblErrorDatePaid.setForeground(new java.awt.Color(244, 67, 54));
        jScrollPane1.setViewportView(lblErrorDatePaid);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Mailbtn)
                                .addGap(40, 40, 40)
                                .addComponent(ytubebtn))
                            .addComponent(jLabel_inven2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblType1)
                            .addComponent(lblType)
                            .addComponent(lblinvoiceno)
                            .addComponent(lblCompany))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtInvoiceNo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblErrorInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblErrorAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbTenant, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(calDateCreated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Mailbtn)
                            .addComponent(ytubebtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_inven2))
                    .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblType)
                    .addComponent(cmbTenant, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblType1)
                    .addComponent(calDateCreated, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblinvoiceno)
                    .addComponent(lblErrorAmount))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblErrorInvoice)
                    .addComponent(lblCompany)
                    .addComponent(txtInvoiceNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // Return to the PaymentScreen when the "Back" button is clicked
        new PaymentScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
      // exsits the application
        System.exit(0);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // Get user input
        String selectedTenantName = (String) cmbTenant.getSelectedItem();

        // Get tenant ID from TenantManager based on selected name
        int tenantID = paymentManager.getTenantIDByName(selectedTenantName);
        // Get the selected item from the combDetails JComboBox 
        LocalDate datecreated = calDateCreated.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        String invoiceNo = txtInvoiceNo.getText();      // get the value entered in the surname field
        String AmountText = txtAmount.getText();        // get the value enterd in the amount field
        double Amount;
        try {
            // Clean the AmountText by removing currency symbols and commas
            AmountText = AmountText.replaceAll("[^\\d.]", "");

            // Parse the cleaned AmountText to a double
            Amount = Double.parseDouble(AmountText);
        } catch (NumberFormatException e) {
            lblErrorAmount.setText("Amount must be a valid number.");
            return;
        }

        // Data Validation
        DataValidation valid = new DataValidation();           // create a new DataValidation object to validate the user input
        lblErrorAmount.setText(valid.checkAmount(AmountText));         // check if the Amount input is valid and set the error message if not
        lblErrorInvoice.setText(valid.checkInvoice(invoiceNo));         // check if the Invoice input is valid and set the error message if not
        lblErrorDatePaid.setText(valid.checkPaymentDate(datecreated)); // check if the date of payment input is valid and set the error message if not

        // Check if Expense already exists
        if (valid.isValid()) {
            if (valid.expenseExists(invoiceNo, 0)) {
                // Display an error message if the owner with the given email already exists
                JOptionPane.showMessageDialog(null, "Payment already exists.");
                return;
            } else {
                // Create a new Owner object and add it to the database
                Payment payment = new Payment(tenantID, Amount, invoiceNo, datecreated);
                PaymentManager Pm = new PaymentManager();
                Pm.addPayment(payment);
                JOptionPane.showMessageDialog(null, "Payment has been added");   // Display a message to the user that the owner has been successfully added

                // Close the add owner screen and open the owner screen
                new PaymentScreen().setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
       // minimises the application
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jButton11MouseClicked

    private void ytubebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ytubebtnActionPerformed
        try {
            String url = "https://vimeo.com/994576038#t=6m42s.";
            // Use Desktop class to open the URL
            if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)) {
                Desktop.getDesktop().browse(new URI(url));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_ytubebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPaymentScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPaymentScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPaymentScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPaymentScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPaymentScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Mailbtn;
    private swing.CustomButtonGradient btnAdd;
    private swing.CustomButtonGradient btnBack1;
    private com.toedter.calendar.JCalendar calDateCreated;
    private javax.swing.JComboBox<String> cmbTenant;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel_inven2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCompany;
    private javax.swing.JLabel lblErrorAmount;
    private javax.swing.JTextPane lblErrorDatePaid;
    private javax.swing.JLabel lblErrorInvoice;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel lblType1;
    private javax.swing.JLabel lblinvoiceno;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtInvoiceNo;
    private javax.swing.JButton ytubebtn;
    // End of variables declaration//GEN-END:variables
}
