
package view;

import classes.DataValidation;
import classes.TenantManager;
import classes.Tenant;
import java.awt.Desktop;
import java.net.URI;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Liron
 */
public class AddTenantScreen extends javax.swing.JFrame {

    private TenantManager tenantManager;

    /**
     * Creates new form NewJFrame
     */
    public AddTenantScreen() {
        initComponents();
        // cmbApartment = new JComboBox<>();
        tenantManager = new TenantManager();
        populateComboBox();

    }

    private void populateComboBox() {
        ArrayList<Integer> PropertyIDs = tenantManager.getPropertyIDs();
        //  System.out.println("Unit numbers: " + PropertyIDs); // Debugging line

        // Populate the combo box model
        Integer[] PropertyIDsArray = PropertyIDs.toArray(new Integer[0]);
        cmbApartment.setModel(new DefaultComboBoxModel<>(PropertyIDsArray));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mailbtn = new javax.swing.JButton();
        ytubebtn = new javax.swing.JButton();
        jLabel_inven2 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Mailbtn1 = new javax.swing.JButton();
        ytubebtn1 = new javax.swing.JButton();
        jLabel_inven3 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        lblHeading = new javax.swing.JLabel();
        btnBack1 = new swing.CustomButtonGradient();
        lblAppartment = new javax.swing.JLabel();
        cmbApartment = new javax.swing.JComboBox<>();
        lblLeaseStartDate = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblPhoneNumber = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        btnAdd = new swing.CustomButtonGradient();
        lblinvoiceno1 = new javax.swing.JLabel();
        txtMiddleName = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblinvoiceno2 = new javax.swing.JLabel();
        txtSurname = new javax.swing.JTextField();
        lblLeaseStartDate1 = new javax.swing.JLabel();
        CalLeaseStartDate = new com.toedter.calendar.JDateChooser();
        CalDOB = new com.toedter.calendar.JDateChooser();
        lblErrorSurname = new javax.swing.JLabel();
        lblErrorFirstName = new javax.swing.JLabel();
        lblErrorLeaseStartDate = new javax.swing.JLabel();
        lblErrorMiddleName = new javax.swing.JLabel();
        lblErrorEmail = new javax.swing.JLabel();
        lblErrorDOB = new javax.swing.JLabel();
        lblErrorPhoneNumber = new javax.swing.JLabel();

        Mailbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Secured_Letter_32px.png"))); // NOI18N
        Mailbtn.setToolTipText("Email");
        Mailbtn.setBorder(null);
        Mailbtn.setBorderPainted(false);
        Mailbtn.setContentAreaFilled(false);
        Mailbtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Secured_Letter_32px_2.png"))); // NOI18N

        ytubebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_YouTube_32px.png"))); // NOI18N
        ytubebtn.setToolTipText("YouTube");
        ytubebtn.setBorder(null);
        ytubebtn.setBorderPainted(false);
        ytubebtn.setContentAreaFilled(false);
        ytubebtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_YouTube_32px_1.png"))); // NOI18N

        jLabel_inven2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel_inven2.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven2.setText("support         Help");

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Minus_32px_1.png"))); // NOI18N
        jButton11.setToolTipText("Minimize");
        jButton11.setBorder(null);
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setFocusPainted(false);
        jButton11.setRequestFocusEnabled(false);
        jButton11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Minus_30px_3.png"))); // NOI18N
        jButton11.setVerifyInputWhenFocusTarget(false);
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_32px.png"))); // NOI18N
        jButton10.setToolTipText("Close");
        jButton10.setBorder(null);
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setRequestFocusEnabled(false);
        jButton10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_30px_3.png"))); // NOI18N
        jButton10.setVerifyInputWhenFocusTarget(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(21, 25, 28));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(21, 25, 28));

        Mailbtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Secured_Letter_32px.png"))); // NOI18N
        Mailbtn1.setToolTipText("Email");
        Mailbtn1.setBorder(null);
        Mailbtn1.setBorderPainted(false);
        Mailbtn1.setContentAreaFilled(false);
        Mailbtn1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Secured_Letter_32px_2.png"))); // NOI18N

        ytubebtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_YouTube_32px.png"))); // NOI18N
        ytubebtn1.setToolTipText("YouTube");
        ytubebtn1.setBorder(null);
        ytubebtn1.setBorderPainted(false);
        ytubebtn1.setContentAreaFilled(false);
        ytubebtn1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_YouTube_32px_1.png"))); // NOI18N
        ytubebtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ytubebtn1ActionPerformed(evt);
            }
        });

        jLabel_inven3.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel_inven3.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven3.setText("support         Help");

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Minus_32px_1.png"))); // NOI18N
        jButton12.setToolTipText("Minimize");
        jButton12.setBorder(null);
        jButton12.setBorderPainted(false);
        jButton12.setContentAreaFilled(false);
        jButton12.setFocusPainted(false);
        jButton12.setRequestFocusEnabled(false);
        jButton12.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Minus_30px_3.png"))); // NOI18N
        jButton12.setVerifyInputWhenFocusTarget(false);
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_32px.png"))); // NOI18N
        jButton13.setToolTipText("Close");
        jButton13.setBorder(null);
        jButton13.setBorderPainted(false);
        jButton13.setContentAreaFilled(false);
        jButton13.setRequestFocusEnabled(false);
        jButton13.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_30px_3.png"))); // NOI18N
        jButton13.setVerifyInputWhenFocusTarget(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        lblHeading.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lblHeading.setForeground(new java.awt.Color(169, 224, 49));
        lblHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeading.setText("ADD Tenant");
        lblHeading.setMaximumSize(new java.awt.Dimension(257, 42));
        lblHeading.setMinimumSize(new java.awt.Dimension(257, 42));

        btnBack1.setForeground(new java.awt.Color(0, 0, 0));
        btnBack1.setText("Back");
        btnBack1.setColor1(new java.awt.Color(15, 214, 79));
        btnBack1.setColor2(new java.awt.Color(248, 239, 66));
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        lblAppartment.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblAppartment.setForeground(new java.awt.Color(169, 224, 49));
        lblAppartment.setText("PropertyID:");

        cmbApartment.setBackground(new java.awt.Color(21, 25, 28));
        cmbApartment.setForeground(new java.awt.Color(169, 224, 49));
        cmbApartment.setMaximumRowCount(100);
        cmbApartment.setModel(new javax.swing.DefaultComboBoxModel<>(new Integer[] { 1, 2, 3, 4 }));
        cmbApartment.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(169, 224, 49)));
        cmbApartment.setOpaque(true);
        cmbApartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbApartmentActionPerformed(evt);
            }
        });

        lblLeaseStartDate.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblLeaseStartDate.setForeground(new java.awt.Color(169, 224, 49));
        lblLeaseStartDate.setText("LeaseStartDate:");

        lblEmail.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(169, 224, 49));
        lblEmail.setText("Email:");

        txtEmail.setBackground(new java.awt.Color(31, 36, 42));
        txtEmail.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        txtEmail.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtEmailMouseMoved(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        lblPhoneNumber.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblPhoneNumber.setForeground(new java.awt.Color(169, 224, 49));
        lblPhoneNumber.setText("PhoneNumber:");

        txtPhoneNumber.setBackground(new java.awt.Color(31, 36, 42));
        txtPhoneNumber.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txtPhoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        txtPhoneNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        txtPhoneNumber.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtPhoneNumberMouseMoved(evt);
            }
        });
        txtPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumberActionPerformed(evt);
            }
        });

        btnAdd.setForeground(new java.awt.Color(0, 0, 0));
        btnAdd.setText("Add Tenant");
        btnAdd.setColor1(new java.awt.Color(169, 224, 49));
        btnAdd.setColor2(new java.awt.Color(169, 224, 49));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblinvoiceno1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblinvoiceno1.setForeground(new java.awt.Color(169, 224, 49));
        lblinvoiceno1.setText("Middle Name:");

        txtMiddleName.setBackground(new java.awt.Color(31, 36, 42));
        txtMiddleName.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txtMiddleName.setForeground(new java.awt.Color(255, 255, 255));
        txtMiddleName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));

        lblFirstName.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(169, 224, 49));
        lblFirstName.setText("First Name:");

        txtFirstName.setBackground(new java.awt.Color(31, 36, 42));
        txtFirstName.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txtFirstName.setForeground(new java.awt.Color(255, 255, 255));
        txtFirstName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        txtFirstName.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtFirstNameMouseMoved(evt);
            }
        });
        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });

        lblinvoiceno2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblinvoiceno2.setForeground(new java.awt.Color(169, 224, 49));
        lblinvoiceno2.setText("Surname:");

        txtSurname.setBackground(new java.awt.Color(31, 36, 42));
        txtSurname.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txtSurname.setForeground(new java.awt.Color(255, 255, 255));
        txtSurname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));

        lblLeaseStartDate1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblLeaseStartDate1.setForeground(new java.awt.Color(169, 224, 49));
        lblLeaseStartDate1.setText("DOB:");

        CalLeaseStartDate.setBackground(new java.awt.Color(31, 36, 42));
        CalLeaseStartDate.setForeground(new java.awt.Color(169, 224, 49));
        CalLeaseStartDate.setOpaque(false);

        CalDOB.setBackground(new java.awt.Color(31, 36, 42));
        CalDOB.setForeground(new java.awt.Color(169, 224, 49));

        lblErrorSurname.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblErrorSurname.setForeground(new java.awt.Color(244, 67, 54));
        lblErrorSurname.setText("*");

        lblErrorFirstName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblErrorFirstName.setForeground(new java.awt.Color(244, 67, 54));
        lblErrorFirstName.setText("*");

        lblErrorLeaseStartDate.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblErrorLeaseStartDate.setForeground(new java.awt.Color(244, 67, 54));
        lblErrorLeaseStartDate.setText("*");

        lblErrorMiddleName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblErrorMiddleName.setForeground(new java.awt.Color(244, 67, 54));

        lblErrorEmail.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblErrorEmail.setForeground(new java.awt.Color(244, 67, 54));
        lblErrorEmail.setText("*");

        lblErrorDOB.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblErrorDOB.setForeground(new java.awt.Color(244, 67, 54));
        lblErrorDOB.setText("*");

        lblErrorPhoneNumber.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblErrorPhoneNumber.setForeground(new java.awt.Color(244, 67, 54));
        lblErrorPhoneNumber.setText("*");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 857, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLeaseStartDate)
                                    .addComponent(lblinvoiceno1)
                                    .addComponent(lblinvoiceno2)
                                    .addComponent(lblAppartment)
                                    .addComponent(lblFirstName)
                                    .addComponent(lblEmail)
                                    .addComponent(lblPhoneNumber)
                                    .addComponent(lblLeaseStartDate1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFirstName)
                                    .addComponent(cmbApartment, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSurname)
                                    .addComponent(txtMiddleName)
                                    .addComponent(CalLeaseStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEmail)
                                    .addComponent(txtPhoneNumber)
                                    .addComponent(CalDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblErrorFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblErrorMiddleName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblErrorSurname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblErrorLeaseStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblErrorEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblErrorPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblErrorDOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(145, 145, 145)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel_inven3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Mailbtn1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ytubebtn1)))
                                .addGap(97, 97, 97)
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, 0)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ytubebtn1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Mailbtn1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_inven3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblFirstName)
                        .addComponent(lblErrorFirstName)))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblinvoiceno1)
                    .addComponent(txtMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorMiddleName))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblinvoiceno2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblErrorSurname)))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAppartment)
                    .addComponent(cmbApartment, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLeaseStartDate)
                    .addComponent(CalLeaseStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorLeaseStartDate))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblErrorEmail))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPhoneNumber)
                            .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblErrorPhoneNumber))
                        .addGap(21, 21, 21)
                        .addComponent(lblLeaseStartDate1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblErrorDOB)
                        .addComponent(CalDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed

    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // Return to the ExpenseScreen when the "Back" button is clicked
        new TenantScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void cmbApartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbApartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbApartmentActionPerformed

    private void txtEmailMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailMouseMoved

    }//GEN-LAST:event_txtEmailMouseMoved

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtPhoneNumberMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPhoneNumberMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberMouseMoved

    private void txtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // Get user input
        String firstName = txtFirstName.getText();
        String middleName = txtMiddleName.getText();
        String surname = txtSurname.getText();
        int propertyID = (int) cmbApartment.getSelectedItem();
        // Get the selected date from JDateChooser
        Date LeaseStartDate = CalLeaseStartDate.getDate();

        // If no date is selected, use today's date
        if (LeaseStartDate == null) {
            LeaseStartDate = new Date(); // Default to today's date
            CalLeaseStartDate.setDate(LeaseStartDate); // Optionally update the JDateChooser
        }

        // Convert selectedDate to LocalDate
        LocalDate leaseStartDate = LeaseStartDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

        String leaseStartDatetext = leaseStartDate.toString();
        // Retrieve the date from the JDateChooser component
        Date dobDate = CalDOB.getDate();

        // Check if the date is null
        if (dobDate == null) {
            // If no date is selected, set it to todays date
            dobDate = new Date();
            CalDOB.setDate(dobDate);
           
        }

        // Convert the date to LocalDate if necessary (or use directly)
        LocalDate dob = dobDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

        String dobtext = dob.toString();

        String email = txtEmail.getText();
        String PhoneNumber = txtPhoneNumber.getText();
        if (middleName == null || middleName.isEmpty()) {
            middleName = "\u200B\u200B\u200B"; // Three invisible characters
        }

// Data Validation
        DataValidation valid = new DataValidation();

        lblErrorFirstName.setText(valid.checkFirstName(firstName));         // check if the Name input is valid and set the error message if not
        lblErrorMiddleName.setText(valid.checkMiddleName(middleName));         // check if the Middlename input is valid and set the error message if not
        lblErrorSurname.setText(valid.checkLastName(surname));         // check if the Surname input is valid and set the error message if not
        lblErrorLeaseStartDate.setText(valid.checkLeaseStartDate(leaseStartDatetext));         // check if the LeaseStartDate input is valid and set the error message if not
        lblErrorEmail.setText(valid.checkEmail(email));                                    // check if the PhoneNumber input is valid and set the error message if not
        lblErrorPhoneNumber.setText(valid.checkPhone(PhoneNumber));         // check if the PhoneNumber input is valid and set the error message if not
        lblErrorDOB.setText(valid.checkDOB(dobtext));         // check if the dob input is valid and set the error message if not

// Check if Tenant already exists
        if (valid.isValid()) {
            if (valid.tenantExists(email, 0)) {
                // Display an error message if the tenant with the given email already exists
                JOptionPane.showMessageDialog(null, "Tenant already exists.");
                return;
            } else {
                // Create a new Tenant object and add it to the database
                Tenant tenant = new Tenant(firstName, middleName, surname, propertyID, leaseStartDate, dob, email, PhoneNumber);
                // Create a new Owner object and add it to the database

                TenantManager Tm = new TenantManager();
                Tm.addTenant(tenant);
                JOptionPane.showMessageDialog(null, "Tenant has been added");   // Display a message to the user that the owner has been successfully added

                // Close the add owner screen and open the owner screen
                new TenantScreen().setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtFirstNameMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFirstNameMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameMouseMoved

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void ytubebtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ytubebtn1ActionPerformed
         try {
            String url = "https://vimeo.com/994576038#t=4m55s.";
            // Use Desktop class to open the URL
            if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)) {
                Desktop.getDesktop().browse(new URI(url));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_ytubebtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTenantScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTenantScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTenantScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTenantScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTenantScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser CalDOB;
    private com.toedter.calendar.JDateChooser CalLeaseStartDate;
    private javax.swing.JButton Mailbtn;
    private javax.swing.JButton Mailbtn1;
    private swing.CustomButtonGradient btnAdd;
    private swing.CustomButtonGradient btnBack1;
    private javax.swing.JComboBox<Integer> cmbApartment;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JLabel jLabel_inven2;
    private javax.swing.JLabel jLabel_inven3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAppartment;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblErrorDOB;
    private javax.swing.JLabel lblErrorEmail;
    private javax.swing.JLabel lblErrorFirstName;
    private javax.swing.JLabel lblErrorLeaseStartDate;
    private javax.swing.JLabel lblErrorMiddleName;
    private javax.swing.JLabel lblErrorPhoneNumber;
    private javax.swing.JLabel lblErrorSurname;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblLeaseStartDate;
    private javax.swing.JLabel lblLeaseStartDate1;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblinvoiceno1;
    private javax.swing.JLabel lblinvoiceno2;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtMiddleName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtSurname;
    private javax.swing.JButton ytubebtn;
    private javax.swing.JButton ytubebtn1;
    // End of variables declaration//GEN-END:variables
}
