    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
// Package declaration for the view components of the application
package view;

// Import necessary classes for GUI and data handling
import classes.DataValidation; // Import for data validation utilities (currently not used in this class)
import classes.TenantManager; // Import for managing tenant data and operations
import java.awt.Desktop; // Import for desktop operations (not used in this class)
import java.io.IOException; // Import for handling IOExceptions (not used in this class)
import java.net.URI; // Import for handling URIs (not used in this class)
import java.net.URISyntaxException; // Import for handling URI syntax exceptions (not used in this class)
import java.text.ParseException; // Import for handling parsing exceptions when converting strings to dates
import java.text.SimpleDateFormat; // Import for date formatting and parsing
import java.time.LocalDate; // Import for representing dates without time
import java.time.ZoneId; // Import for time zone handling (not used in this class)
import java.util.ArrayList; // Import for using ArrayLists to store property IDs
import java.util.Date; // Import for using Date objects to represent dates
import java.util.logging.Level; // Import for setting log levels
import java.util.logging.Logger; // Import for logging messages and exceptions
import javax.swing.DefaultComboBoxModel; // Import for creating a model for the combo box
import javax.swing.JOptionPane; // Import for showing dialog boxes

/**
 * EditTenantScreen is a JFrame that allows editing of tenant details.
 * It populates fields with the selected tenant's information and allows for updates.
 */
public class EditTenantScreen extends javax.swing.JFrame {

    // Manager class for handling tenant-related operations
    private TenantManager tenantManager;

    /**
     * Creates new form EditTenantScreen.
     * Initializes the form and populates the fields with selected tenant's data.
     */
    public EditTenantScreen() {
        initComponents();
        
        // Populate fields with the details of the selected tenant
        txtFirstName.setText(TenantScreen.tenantSelected.getFirstName());
        txtMiddleName.setText(TenantScreen.tenantSelected.getMiddleName());
        txtSurname.setText(TenantScreen.tenantSelected.getSurname());
        
        // Set the selected property ID in the apartment combo box
        cmbApartment.setSelectedItem(TenantScreen.tenantSelected.getPropertyIDsFromTenants());

        // Parse and set the lease start date
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        try {
            Date LeaseStartDate = df.parse(TenantScreen.tenantSelected.getLeaseStartDate());
            CalLeaseStartDate.setDate(LeaseStartDate);
        } catch (ParseException ex) {
            Logger.getLogger(EditTenantScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        // Parse and set the date of birth
        try {
            Date DOB = df.parse(TenantScreen.tenantSelected.getDob());
            CalDOB.setDate(DOB);
        } catch (ParseException ex) {
            Logger.getLogger(EditTenantScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        // Set other tenant details
        txtEmail.setText(TenantScreen.tenantSelected.getEmail());
        txtPhoneNumber.setText(TenantScreen.tenantSelected.getPhoneNumber());
        
        // Initialize the TenantManager and populate the combo box with available apartments
        tenantManager = new TenantManager();
        populateComboBox();
    }

    /**
     * Populates the apartment combo box with available property IDs from the TenantManager.
     */
    private void populateComboBox() {
        // Retrieve list of property IDs from TenantManager
        ArrayList<Integer> PropertyIDsFromTenants = tenantManager.getPropertyIDsFromTenants();

        // Convert ArrayList to Array for DefaultComboBoxModel
        Integer[] PropertyIDsFromTenantsArray = PropertyIDsFromTenants.toArray(new Integer[0]);

        // Set the model for the combo box
        cmbApartment.setModel(new DefaultComboBoxModel<>(PropertyIDsFromTenantsArray));
    }


    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mailbtn = new javax.swing.JButton();
        ytubebtn = new javax.swing.JButton();
        jLabel_inven2 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        lblErrorMiddleName = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Mailbtn1 = new javax.swing.JButton();
        ytubebtn1 = new javax.swing.JButton();
        jLabel_inven3 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        lblHeading = new javax.swing.JLabel();
        btnBack1 = new swing.CustomButtonGradient();
        lblAppartment = new javax.swing.JLabel();
        cmbApartment = new javax.swing.JComboBox<>();
        lblLeaseStartDate = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblPhoneNumber = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        btnEdit = new swing.CustomButtonGradient();
        lblinvoiceno1 = new javax.swing.JLabel();
        txtMiddleName = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblinvoiceno2 = new javax.swing.JLabel();
        txtSurname = new javax.swing.JTextField();
        lblLeaseStartDate1 = new javax.swing.JLabel();
        CalLeaseStartDate = new com.toedter.calendar.JDateChooser();
        CalDOB = new com.toedter.calendar.JDateChooser();
        lblErrorFirstName = new javax.swing.JLabel();
        lblErrorMiddleName1 = new javax.swing.JLabel();
        lblErrorSurname = new javax.swing.JLabel();
        lblErrorLeaseStartDate = new javax.swing.JLabel();
        lblErrorEmail = new javax.swing.JLabel();
        lblErrorPhoneNumber = new javax.swing.JLabel();
        lblErrorDOB = new javax.swing.JLabel();

        Mailbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Secured_Letter_32px.png"))); // NOI18N
        Mailbtn.setToolTipText("Email");
        Mailbtn.setBorder(null);
        Mailbtn.setBorderPainted(false);
        Mailbtn.setContentAreaFilled(false);
        Mailbtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Secured_Letter_32px_2.png"))); // NOI18N

        ytubebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_YouTube_32px.png"))); // NOI18N
        ytubebtn.setToolTipText("YouTube");
        ytubebtn.setBorder(null);
        ytubebtn.setBorderPainted(false);
        ytubebtn.setContentAreaFilled(false);
        ytubebtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_YouTube_32px_1.png"))); // NOI18N

        jLabel_inven2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel_inven2.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven2.setText("support         Help");

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Minus_32px_1.png"))); // NOI18N
        jButton11.setToolTipText("Minimize");
        jButton11.setBorder(null);
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setFocusPainted(false);
        jButton11.setRequestFocusEnabled(false);
        jButton11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Minus_30px_3.png"))); // NOI18N
        jButton11.setVerifyInputWhenFocusTarget(false);
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_32px.png"))); // NOI18N
        jButton10.setToolTipText("Close");
        jButton10.setBorder(null);
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setRequestFocusEnabled(false);
        jButton10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_30px_3.png"))); // NOI18N
        jButton10.setVerifyInputWhenFocusTarget(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        lblErrorMiddleName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblErrorMiddleName.setForeground(new java.awt.Color(244, 67, 54));
        lblErrorMiddleName.setText("*");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(21, 25, 28));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(21, 25, 28));

        Mailbtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Secured_Letter_32px.png"))); // NOI18N
        Mailbtn1.setToolTipText("Email");
        Mailbtn1.setBorder(null);
        Mailbtn1.setBorderPainted(false);
        Mailbtn1.setContentAreaFilled(false);
        Mailbtn1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Secured_Letter_32px_2.png"))); // NOI18N
        Mailbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mailbtn1ActionPerformed(evt);
            }
        });

        ytubebtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_YouTube_32px.png"))); // NOI18N
        ytubebtn1.setToolTipText("YouTube");
        ytubebtn1.setBorder(null);
        ytubebtn1.setBorderPainted(false);
        ytubebtn1.setContentAreaFilled(false);
        ytubebtn1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_YouTube_32px_1.png"))); // NOI18N
        ytubebtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ytubebtn1ActionPerformed(evt);
            }
        });

        jLabel_inven3.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel_inven3.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven3.setText("support         Help");

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Minus_32px_1.png"))); // NOI18N
        jButton12.setToolTipText("Minimize");
        jButton12.setBorder(null);
        jButton12.setBorderPainted(false);
        jButton12.setContentAreaFilled(false);
        jButton12.setFocusPainted(false);
        jButton12.setRequestFocusEnabled(false);
        jButton12.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Minus_30px_3.png"))); // NOI18N
        jButton12.setVerifyInputWhenFocusTarget(false);
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_32px.png"))); // NOI18N
        jButton13.setToolTipText("Close");
        jButton13.setBorder(null);
        jButton13.setBorderPainted(false);
        jButton13.setContentAreaFilled(false);
        jButton13.setRequestFocusEnabled(false);
        jButton13.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_30px_3.png"))); // NOI18N
        jButton13.setVerifyInputWhenFocusTarget(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        lblHeading.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lblHeading.setForeground(new java.awt.Color(169, 224, 49));
        lblHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeading.setText("Edit Tenant");
        lblHeading.setMaximumSize(new java.awt.Dimension(257, 42));
        lblHeading.setMinimumSize(new java.awt.Dimension(257, 42));

        btnBack1.setForeground(new java.awt.Color(0, 0, 0));
        btnBack1.setText("Back");
        btnBack1.setColor1(new java.awt.Color(15, 214, 79));
        btnBack1.setColor2(new java.awt.Color(248, 239, 66));
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        lblAppartment.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblAppartment.setForeground(new java.awt.Color(169, 224, 49));
        lblAppartment.setText("PropertyID:");

        cmbApartment.setBackground(new java.awt.Color(21, 25, 28));
        cmbApartment.setForeground(new java.awt.Color(169, 224, 49));
        cmbApartment.setMaximumRowCount(100);
        cmbApartment.setModel(new javax.swing.DefaultComboBoxModel<>(new Integer[] { 1, 2, 3, 4 }));
        cmbApartment.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(169, 224, 49)));
        cmbApartment.setOpaque(true);
        cmbApartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbApartmentActionPerformed(evt);
            }
        });

        lblLeaseStartDate.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblLeaseStartDate.setForeground(new java.awt.Color(169, 224, 49));
        lblLeaseStartDate.setText("LeaseStartDate:");

        lblEmail.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(169, 224, 49));
        lblEmail.setText("Email:");

        txtEmail.setBackground(new java.awt.Color(31, 36, 42));
        txtEmail.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        txtEmail.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtEmailMouseMoved(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        lblPhoneNumber.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblPhoneNumber.setForeground(new java.awt.Color(169, 224, 49));
        lblPhoneNumber.setText("PhoneNumber:");

        txtPhoneNumber.setBackground(new java.awt.Color(31, 36, 42));
        txtPhoneNumber.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txtPhoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        txtPhoneNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        txtPhoneNumber.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtPhoneNumberMouseMoved(evt);
            }
        });
        txtPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumberActionPerformed(evt);
            }
        });

        btnEdit.setForeground(new java.awt.Color(0, 0, 0));
        btnEdit.setText("Update Tenant");
        btnEdit.setColor1(new java.awt.Color(169, 224, 49));
        btnEdit.setColor2(new java.awt.Color(169, 224, 49));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        lblinvoiceno1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblinvoiceno1.setForeground(new java.awt.Color(169, 224, 49));
        lblinvoiceno1.setText("Middle Name:");

        txtMiddleName.setBackground(new java.awt.Color(31, 36, 42));
        txtMiddleName.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txtMiddleName.setForeground(new java.awt.Color(255, 255, 255));
        txtMiddleName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));

        lblFirstName.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(169, 224, 49));
        lblFirstName.setText("First Name:");

        txtFirstName.setBackground(new java.awt.Color(31, 36, 42));
        txtFirstName.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txtFirstName.setForeground(new java.awt.Color(255, 255, 255));
        txtFirstName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));

        lblinvoiceno2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblinvoiceno2.setForeground(new java.awt.Color(169, 224, 49));
        lblinvoiceno2.setText("Surname:");

        txtSurname.setBackground(new java.awt.Color(31, 36, 42));
        txtSurname.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txtSurname.setForeground(new java.awt.Color(255, 255, 255));
        txtSurname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));

        lblLeaseStartDate1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblLeaseStartDate1.setForeground(new java.awt.Color(169, 224, 49));
        lblLeaseStartDate1.setText("DOB:");

        lblErrorFirstName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblErrorFirstName.setForeground(new java.awt.Color(244, 67, 54));
        lblErrorFirstName.setText("*");

        lblErrorMiddleName1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblErrorMiddleName1.setForeground(new java.awt.Color(244, 67, 54));
        lblErrorMiddleName1.setText("*");

        lblErrorSurname.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblErrorSurname.setForeground(new java.awt.Color(244, 67, 54));
        lblErrorSurname.setText("*");

        lblErrorLeaseStartDate.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblErrorLeaseStartDate.setForeground(new java.awt.Color(244, 67, 54));
        lblErrorLeaseStartDate.setText("*");

        lblErrorEmail.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblErrorEmail.setForeground(new java.awt.Color(244, 67, 54));
        lblErrorEmail.setText("*");

        lblErrorPhoneNumber.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblErrorPhoneNumber.setForeground(new java.awt.Color(244, 67, 54));
        lblErrorPhoneNumber.setText("*");

        lblErrorDOB.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblErrorDOB.setForeground(new java.awt.Color(244, 67, 54));
        lblErrorDOB.setText("*");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                                .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(145, 145, 145)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel_inven3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Mailbtn1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ytubebtn1)))
                                .addGap(97, 97, 97))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblinvoiceno2)
                                            .addComponent(lblFirstName)
                                            .addComponent(lblinvoiceno1))
                                        .addGap(60, 60, 60)
                                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblLeaseStartDate)
                                            .addComponent(lblAppartment)
                                            .addComponent(lblEmail)
                                            .addComponent(lblPhoneNumber)
                                            .addComponent(lblLeaseStartDate1))
                                        .addGap(58, 58, 58)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtMiddleName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                            .addComponent(txtSurname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                            .addComponent(cmbApartment, javax.swing.GroupLayout.Alignment.LEADING, 0, 203, Short.MAX_VALUE)
                                            .addComponent(CalLeaseStartDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                            .addComponent(txtPhoneNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                            .addComponent(CalDOB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblErrorFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                                    .addComponent(lblErrorMiddleName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblErrorSurname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblErrorLeaseStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblErrorEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblErrorPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblErrorDOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)))
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ytubebtn1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Mailbtn1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_inven3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFirstName)
                    .addComponent(lblErrorFirstName))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblinvoiceno1)
                    .addComponent(lblErrorMiddleName1))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblErrorSurname))
                    .addComponent(lblinvoiceno2))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbApartment, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAppartment))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLeaseStartDate)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblErrorLeaseStartDate)
                        .addComponent(CalLeaseStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorEmail))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneNumber)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorPhoneNumber))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLeaseStartDate1)
                            .addComponent(CalDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblErrorDOB))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed

    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // Return to the ExpenseScreen when the "Back" button is clicked
        new TenantScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void cmbApartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbApartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbApartmentActionPerformed

    private void txtEmailMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailMouseMoved

    }//GEN-LAST:event_txtEmailMouseMoved

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtPhoneNumberMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPhoneNumberMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberMouseMoved

    private void txtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
// Get user input from the form fields
String firstName = txtFirstName.getText(); // Retrieve the first name
String middleName = txtMiddleName.getText(); // Retrieve the middle name
String surname = txtSurname.getText(); // Retrieve the surname
int propertyID = (int) cmbApartment.getSelectedItem(); // Retrieve the selected property ID from the combo box

// Get the selected lease start date from the JDateChooser component
Date selectedDate = CalLeaseStartDate.getDate();

// If no date is selected, use today's date
if (selectedDate == null) {
    selectedDate = new Date(); // Default to today's date
    CalLeaseStartDate.setDate(selectedDate); // Optionally update the JDateChooser
}

// Convert selectedDate to LocalDate for easier manipulation
LocalDate leaseStartDate = selectedDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
String leaseStartDatetext = leaseStartDate.toString(); // Convert LocalDate to string format

// Retrieve the date of birth from the JDateChooser component
Date dobDate = CalDOB.getDate();

// Check if the date of birth is null
if (dobDate == null) {
    // If no date is selected, set the error message and return
    lblErrorDOB.setText("Date of Birth cannot be left blank.");
}

// Convert the date of birth to LocalDate for easier manipulation
LocalDate dob = dobDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
String dobtext = dob.toString(); // Convert LocalDate to string format

// Retrieve other fields
String email = txtEmail.getText(); // Retrieve the email address
String PhoneNumber = txtPhoneNumber.getText(); // Retrieve the phone number

// Data Validation
DataValidation valid = new DataValidation(); // Create a DataValidation object to check input validity

// Perform validation checks and set error messages if inputs are invalid
lblErrorFirstName.setText(valid.checkFirstName(firstName)); // Check first name validity
lblErrorMiddleName.setText(valid.checkMiddleName(middleName)); // Check middle name validity
lblErrorSurname.setText(valid.checkLastName(surname)); // Check surname validity
lblErrorLeaseStartDate.setText(valid.checkLeaseStartDate(leaseStartDatetext)); // Check lease start date validity
lblErrorEmail.setText(valid.checkEmail(email)); // Check email validity
lblErrorPhoneNumber.setText(valid.checkPhone(PhoneNumber)); // Check phone number validity
lblErrorDOB.setText(valid.checkDOB(dobtext)); // Check date of birth validity

// Proceed if all validation checks pass
if (valid.isValid()) {
    TenantManager Tm = new TenantManager(); // Create a TenantManager object to handle tenant operations

    // Check if a tenant with the same email already exists
    if (valid.tenantExists(email, TenantScreen.tenantSelected.getTenantID())) {
        JOptionPane.showMessageDialog(null, "Tenant already exists."); // Show an error message
        return; // Exit the method if tenant already exists
    } else {
        // Confirm with the user if they want to edit the tenant
        int confirmation = JOptionPane.showConfirmDialog(null, "Are you sure you want to edit this Tenant?", "Edit Confirmation", JOptionPane.YES_NO_OPTION);
        if (confirmation == JOptionPane.YES_OPTION) {
            // Update the selected tenant's details
            TenantScreen.tenantSelected.setFirstName(firstName);
            TenantScreen.tenantSelected.setMiddleName(middleName);
            TenantScreen.tenantSelected.setSurname(surname);
            TenantScreen.tenantSelected.setPropertyID(propertyID);
            TenantScreen.tenantSelected.setLeaseStartDate(leaseStartDate);
            TenantScreen.tenantSelected.setDob(dob);
            TenantScreen.tenantSelected.setEmail(email);
            TenantScreen.tenantSelected.setPhoneNumber(PhoneNumber);

            // Save the changes to the tenant
            Tm.editTenant(TenantScreen.tenantSelected);

            // Notify the user of success
            JOptionPane.showMessageDialog(null, "Successfully edited the Tenant");

            // Open the TenantScreen and close the current form
            new TenantScreen().setVisible(true);
            dispose();
        }
    }
}
 

    }//GEN-LAST:event_btnEditActionPerformed

    private void ytubebtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ytubebtn1ActionPerformed
         try {
            String url = "https://vimeo.com/994576038#t=5m29s.";
            // Use Desktop class to open the URL
            if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)) {
                Desktop.getDesktop().browse(new URI(url));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_ytubebtn1ActionPerformed

    private void Mailbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mailbtn1ActionPerformed
                // Declare a Desktop object
Desktop desktop;

if (Desktop.isDesktopSupported() // Check if the Desktop class is supported on the current platform
    && (desktop = Desktop.getDesktop()).isSupported(Desktop.Action.MAIL)) { // Check if the MAIL action is supported by the Desktop class
    try {
        // Create a URI object with the mailto URL
        URI mailto = new URI("mailto:your-email@example.com?subject=Apartment%20rental%20manemgment%20support:");
        
        // Use the Desktop class to open the default mail client with the mailto URL
        desktop.mail(mailto);
    } catch (URISyntaxException ex) {
        // Log the URISyntaxException if it occurs
        Logger.getLogger(SplashScreen.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IOException ex) {
        // Log the IOException if it occurs
        Logger.getLogger(SplashScreen.class.getName()).log(Level.SEVERE, null, ex);
    }
} else {
    // If the Desktop class or MAIL action is not supported, throw a RuntimeException
    throw new RuntimeException("desktop doesn't support mailto; mail is dead anyway ;)");
}

    }//GEN-LAST:event_Mailbtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTenantScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTenantScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTenantScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTenantScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTenantScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser CalDOB;
    private com.toedter.calendar.JDateChooser CalLeaseStartDate;
    private javax.swing.JButton Mailbtn;
    private javax.swing.JButton Mailbtn1;
    private swing.CustomButtonGradient btnBack1;
    private swing.CustomButtonGradient btnEdit;
    private javax.swing.JComboBox<Integer> cmbApartment;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JLabel jLabel_inven2;
    private javax.swing.JLabel jLabel_inven3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAppartment;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblErrorDOB;
    private javax.swing.JLabel lblErrorEmail;
    private javax.swing.JLabel lblErrorFirstName;
    private javax.swing.JLabel lblErrorLeaseStartDate;
    private javax.swing.JLabel lblErrorMiddleName;
    private javax.swing.JLabel lblErrorMiddleName1;
    private javax.swing.JLabel lblErrorPhoneNumber;
    private javax.swing.JLabel lblErrorSurname;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblLeaseStartDate;
    private javax.swing.JLabel lblLeaseStartDate1;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblinvoiceno1;
    private javax.swing.JLabel lblinvoiceno2;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtMiddleName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtSurname;
    private javax.swing.JButton ytubebtn;
    private javax.swing.JButton ytubebtn1;
    // End of variables declaration//GEN-END:variables
}
