
package view;

import classes.DataValidation;
import classes.ExpenseManager;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 * EditExpenseScreen class for editing expense details in the application.
 * This class extends javax.swing.JFrame and provides a GUI for editing expense information.
 * It initializes with the selected expense details pre-filled in the form fields.
 * 
 * @author Liron
 */
public class EditExpenseScreen extends javax.swing.JFrame {

    /**
     * Creates new form EditExpenseScreen
     * Initializes the components and auto-fills them with the selected expense's details.
     */
    public EditExpenseScreen() {
        initComponents(); // Initialize form components

        // Auto-fill components with selected expense's details
        // Set the selected item in the details combo box to the selected expense's details
        cmbDetails.setSelectedItem(ExpenseScreen.expenseSelected.getDetails());
        // Set the company text field to the selected expense's company
        txtCompany.setText(ExpenseScreen.expenseSelected.getCompany());

        // Format the payment date from string to Date object
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        try {
            // Parse the payment date string to a Date object
            Date paymentdate = df.parse(ExpenseScreen.expenseSelected.getPaymentDate());
            // Set the calendar date picker to the parsed payment date
            caldate.setDate(paymentdate);
        } catch (ParseException ex) {
            // Log any parsing exceptions
            Logger.getLogger(EditExpenseScreen.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Set the invoice number text field to the selected expense's invoice number
        txtinvoiceno.setText(ExpenseScreen.expenseSelected.getInvoiceNo());
        // Set the amount text field to the selected expense's amount
        txtAmount.setText(String.valueOf(ExpenseScreen.expenseSelected.getAmount()));

        // Define an array of expense details to populate the details combo box
        String[] columnDetails = {
            "Rent", "Utilities (Electricity)", "Utilities (Water)", "Internet",
            "Maintenance/Repairs", "Insurance", "Property Taxes", "HOA Fees",
            "Cleaning Services", "Security Deposit", "Cable TV", "Parking Fees",
            "Pet Fees", "Trash Removal", "Furniture Rental", "Moving Expenses",
            "Legal Fees", "Key Replacement", "Pet Damage Repair", "Miscellaneous"
        };
        // Set the model of the details combo box to the array of column details
        cmbDetails.setModel(new DefaultComboBoxModel<>(columnDetails));
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblHeading = new javax.swing.JLabel();
        btnBack1 = new swing.CustomButtonGradient();
        Mailbtn = new javax.swing.JButton();
        ytubebtn = new javax.swing.JButton();
        jLabel_inven2 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        lblType = new javax.swing.JLabel();
        cmbDetails = new javax.swing.JComboBox<>();
        lblType1 = new javax.swing.JLabel();
        caldate = new com.toedter.calendar.JCalendar();
        lblinvoiceno = new javax.swing.JLabel();
        txtinvoiceno = new javax.swing.JTextField();
        lblCompany = new javax.swing.JLabel();
        txtCompany = new javax.swing.JTextField();
        lblDOB = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        btnAdd = new swing.CustomButtonGradient();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblErrorPaymentDate = new javax.swing.JTextPane();
        lblErrorInvoice = new javax.swing.JLabel();
        lblErrorCompany = new javax.swing.JLabel();
        lblErrorAmount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(21, 25, 28));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(21, 25, 28));

        lblHeading.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lblHeading.setForeground(new java.awt.Color(169, 224, 49));
        lblHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeading.setText("EDIT Expense");

        btnBack1.setForeground(new java.awt.Color(0, 0, 0));
        btnBack1.setText("Back");
        btnBack1.setColor1(new java.awt.Color(15, 214, 79));
        btnBack1.setColor2(new java.awt.Color(248, 239, 66));
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        Mailbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Secured_Letter_32px.png"))); // NOI18N
        Mailbtn.setToolTipText("Email");
        Mailbtn.setBorder(null);
        Mailbtn.setBorderPainted(false);
        Mailbtn.setContentAreaFilled(false);
        Mailbtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Secured_Letter_32px_2.png"))); // NOI18N
        Mailbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MailbtnActionPerformed(evt);
            }
        });

        ytubebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_YouTube_32px.png"))); // NOI18N
        ytubebtn.setToolTipText("YouTube");
        ytubebtn.setBorder(null);
        ytubebtn.setBorderPainted(false);
        ytubebtn.setContentAreaFilled(false);
        ytubebtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_YouTube_32px_1.png"))); // NOI18N
        ytubebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ytubebtnActionPerformed(evt);
            }
        });

        jLabel_inven2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel_inven2.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven2.setText("support         Help");

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Minus_32px_1.png"))); // NOI18N
        jButton11.setToolTipText("Minimize");
        jButton11.setBorder(null);
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setFocusPainted(false);
        jButton11.setRequestFocusEnabled(false);
        jButton11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Minus_30px_3.png"))); // NOI18N
        jButton11.setVerifyInputWhenFocusTarget(false);
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_32px.png"))); // NOI18N
        jButton10.setToolTipText("Close");
        jButton10.setBorder(null);
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setRequestFocusEnabled(false);
        jButton10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_30px_3.png"))); // NOI18N
        jButton10.setVerifyInputWhenFocusTarget(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        lblType.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblType.setForeground(new java.awt.Color(169, 224, 49));
        lblType.setText("Details:");

        cmbDetails.setBackground(new java.awt.Color(21, 25, 28));
        cmbDetails.setForeground(new java.awt.Color(169, 224, 49));
        cmbDetails.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbDetails.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(169, 224, 49)));
        cmbDetails.setOpaque(true);
        cmbDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDetailsActionPerformed(evt);
            }
        });

        lblType1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblType1.setForeground(new java.awt.Color(169, 224, 49));
        lblType1.setText("Date:");

        caldate.setBackground(new java.awt.Color(204, 153, 0));

        lblinvoiceno.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblinvoiceno.setForeground(new java.awt.Color(169, 224, 49));
        lblinvoiceno.setText("invoice no:");

        txtinvoiceno.setBackground(new java.awt.Color(31, 36, 42));
        txtinvoiceno.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txtinvoiceno.setForeground(new java.awt.Color(255, 255, 255));
        txtinvoiceno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        txtinvoiceno.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtinvoicenoMouseMoved(evt);
            }
        });
        txtinvoiceno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinvoicenoActionPerformed(evt);
            }
        });

        lblCompany.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblCompany.setForeground(new java.awt.Color(169, 224, 49));
        lblCompany.setText("Company:");

        txtCompany.setBackground(new java.awt.Color(31, 36, 42));
        txtCompany.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txtCompany.setForeground(new java.awt.Color(255, 255, 255));
        txtCompany.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        txtCompany.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtCompanyMouseMoved(evt);
            }
        });
        txtCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompanyActionPerformed(evt);
            }
        });

        lblDOB.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblDOB.setForeground(new java.awt.Color(169, 224, 49));
        lblDOB.setText("Amount:");

        txtAmount.setBackground(new java.awt.Color(31, 36, 42));
        txtAmount.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txtAmount.setForeground(new java.awt.Color(255, 255, 255));
        txtAmount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        txtAmount.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtAmountMouseMoved(evt);
            }
        });
        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });

        btnAdd.setForeground(new java.awt.Color(0, 0, 0));
        btnAdd.setText("UpdatePayment");
        btnAdd.setColor1(new java.awt.Color(169, 224, 49));
        btnAdd.setColor2(new java.awt.Color(169, 224, 49));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(null);

        lblErrorPaymentDate.setBackground(new java.awt.Color(21, 25, 28));
        lblErrorPaymentDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 25, 28)));
        lblErrorPaymentDate.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lblErrorPaymentDate.setForeground(new java.awt.Color(244, 67, 54));
        jScrollPane1.setViewportView(lblErrorPaymentDate);

        lblErrorInvoice.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblErrorInvoice.setForeground(new java.awt.Color(244, 67, 54));
        lblErrorInvoice.setText("*");

        lblErrorCompany.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblErrorCompany.setForeground(new java.awt.Color(244, 67, 54));
        lblErrorCompany.setText("*");

        lblErrorAmount.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblErrorAmount.setForeground(new java.awt.Color(244, 67, 54));
        lblErrorAmount.setText("*");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblType)
                    .addComponent(lblType1)
                    .addComponent(lblinvoiceno)
                    .addComponent(lblCompany)
                    .addComponent(lblDOB))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cmbDetails, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(caldate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtinvoiceno, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblErrorAmount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErrorInvoice)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblErrorCompany))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(225, 225, 225)
                .addComponent(lblHeading)
                .addGap(128, 128, 128)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Mailbtn)
                        .addGap(40, 40, 40)
                        .addComponent(ytubebtn))
                    .addComponent(jLabel_inven2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Mailbtn)
                            .addComponent(ytubebtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_inven2))
                    .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHeading))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblType)
                    .addComponent(cmbDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblType1)
                            .addComponent(caldate, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblinvoiceno)
                            .addComponent(txtinvoiceno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblErrorInvoice))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCompany)
                            .addComponent(lblErrorCompany))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDOB)
                            .addComponent(lblErrorAmount))
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(161, 161, 161)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // Return to the ExpenseScreen when the "Back" button is clicked
        new ExpenseScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void cmbDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDetailsActionPerformed

    private void txtinvoicenoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtinvoicenoMouseMoved

    }//GEN-LAST:event_txtinvoicenoMouseMoved

    private void txtinvoicenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinvoicenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtinvoicenoActionPerformed

    private void txtCompanyMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCompanyMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompanyMouseMoved

    private void txtCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompanyActionPerformed

    private void txtAmountMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAmountMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountMouseMoved

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
       // Get user input
String details = cmbDetails.getSelectedItem().toString(); // Get the selected item from the details combo box
String company = txtCompany.getText(); // Get the text from the company text field
LocalDate paymentdate = caldate.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate(); // Get the selected date from the calendar date picker and convert it to LocalDate
String InvoiceNo = txtinvoiceno.getText(); // Get the text from the invoice number text field
String AmountText = txtAmount.getText(); // Get the text from the amount text field
double amount;

try {
    // Clean the AmountText by removing currency symbols and commas
    AmountText = AmountText.replaceAll("[^\\d.]", ""); // Remove any non-digit and non-dot characters from the amount text

    // Parse the cleaned AmountText to a double
    amount = Double.parseDouble(AmountText); // Convert the cleaned amount text to a double
} catch (NumberFormatException e) {
    // If the conversion fails, set the error message on the amount error label and return
    lblErrorAmount.setText("Amount must be a valid number.");
    return;
}

DataValidation valid = new DataValidation(); // Create a new DataValidation object to validate the user input

// Validate each input and set the corresponding error labels
lblErrorPaymentDate.setText(valid.checkPaymentDate(paymentdate)); // Check if the payment date input is valid and set the error message if not
lblErrorCompany.setText(valid.checkCompany(company)); // Check if the company input is valid and set the error message if not
lblErrorAmount.setText(valid.checkAmount(AmountText)); // Check if the amount input is valid and set the error message if not
lblErrorInvoice.setText(valid.checkInvoice(InvoiceNo)); // Check if the invoice number input is valid and set the error message if not

// If all inputs are valid, proceed with editing the expense
if (valid.isValid()) {
    ExpenseManager em = new ExpenseManager(); // Create a new ExpenseManager object to manage expense operations

    // Check if an expense with the same invoice number already exists
    if (valid.expenseExists(InvoiceNo, ExpenseScreen.expenseSelected.getExpenseID())) {
        // If it exists, show a message dialog indicating the expense already exists and return
        JOptionPane.showMessageDialog(null, "Expense already exists.");
        return;
    } else {
        // Confirm the edit action with the user
        int confirmation = JOptionPane.showConfirmDialog(null, "Are you sure you want to edit this expense?", "Edit Confirmation", JOptionPane.YES_NO_OPTION);
        if (confirmation == JOptionPane.YES_OPTION) {
            // If the user confirms, set the new values for the selected expense
            ExpenseScreen.expenseSelected.setDetails(details);
            ExpenseScreen.expenseSelected.setCompany(company);
            ExpenseScreen.expenseSelected.setPaymentDate(paymentdate);
            ExpenseScreen.expenseSelected.setInvoiceNo(InvoiceNo);
            ExpenseScreen.expenseSelected.setAmount(amount);

            // Call the editExpense method to update the expense in the database
            em.editExpense(ExpenseScreen.expenseSelected);

            // Show a message dialog indicating the expense was successfully edited
            JOptionPane.showMessageDialog(null, "Successfully edited the expense");

            // Open the ExpenseScreen and close the current EditExpenseScreen
            new ExpenseScreen().setVisible(true);
            dispose(); // Close the current EditExpenseScreen
        }
    }
}

    }//GEN-LAST:event_btnAddActionPerformed

    private void ytubebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ytubebtnActionPerformed
     try {
    // Define the URL of the video to be opened
    String url = "https://vimeo.com/994576038#t=3m21s.";
    
    // Check if the Desktop class is supported on the current platform and if the BROWSE action is supported
    if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)) {
        // Use the Desktop class to open the URL in the default web browser
        Desktop.getDesktop().browse(new URI(url));
    }
} catch (Exception ex) {
    // Print the stack trace if an exception occurs
    ex.printStackTrace();
}

    }//GEN-LAST:event_ytubebtnActionPerformed

    private void MailbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MailbtnActionPerformed
        // Declare a Desktop object
Desktop desktop;

if (Desktop.isDesktopSupported() // Check if the Desktop class is supported on the current platform
    && (desktop = Desktop.getDesktop()).isSupported(Desktop.Action.MAIL)) { // Check if the MAIL action is supported by the Desktop class
    try {
        // Create a URI object with the mailto URL
        URI mailto = new URI("mailto:your-email@example.com?subject=Apartment%20rental%20manemgment%20support:");
        
        // Use the Desktop class to open the default mail client with the mailto URL
        desktop.mail(mailto);
    } catch (URISyntaxException ex) {
        // Log the URISyntaxException if it occurs
        Logger.getLogger(SplashScreen.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IOException ex) {
        // Log the IOException if it occurs
        Logger.getLogger(SplashScreen.class.getName()).log(Level.SEVERE, null, ex);
    }
} else {
    // If the Desktop class or MAIL action is not supported, throw a RuntimeException
    throw new RuntimeException("desktop doesn't support mailto; mail is dead anyway ;)");
}

    }//GEN-LAST:event_MailbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditExpenseScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditExpenseScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditExpenseScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditExpenseScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditExpenseScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Mailbtn;
    private swing.CustomButtonGradient btnAdd;
    private swing.CustomButtonGradient btnBack1;
    private com.toedter.calendar.JCalendar caldate;
    private javax.swing.JComboBox<String> cmbDetails;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel_inven2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCompany;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblErrorAmount;
    private javax.swing.JLabel lblErrorCompany;
    private javax.swing.JLabel lblErrorInvoice;
    private javax.swing.JTextPane lblErrorPaymentDate;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel lblType1;
    private javax.swing.JLabel lblinvoiceno;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtCompany;
    private javax.swing.JTextField txtinvoiceno;
    private javax.swing.JButton ytubebtn;
    // End of variables declaration//GEN-END:variables
}
