package view;

// Import necessary classes for GUI and functionality
import classes.Property; // Import for handling property-related operations
import classes.PropertyManager; // Import for managing properties
import classes.Tenant; // Import for handling tenant-related operations
import classes.TenantManager; // Import for managing tenants
import filter.SearchOption; // Import for search options (not used in this class)
import filter.SearchOptionEvent; // Import for search option events (not used in this class)
import java.awt.Color; // Import for handling color values
import java.awt.Desktop; // Import for desktop operations
import java.awt.event.ActionEvent; // Import for handling action events
import java.awt.event.ActionListener; // Import for action listeners
import java.awt.print.PageFormat; // Import for page format settings (not used in this class)
import java.awt.print.Paper; // Import for paper settings (not used in this class)
import java.awt.print.PrinterException; // Import for handling printer exceptions
import java.awt.print.PrinterJob; // Import for printer job operations
import java.io.IOException; // Import for handling IOExceptions
import java.net.URI; // Import for handling URIs
import java.net.URISyntaxException; // Import for handling URI syntax exceptions
import java.util.logging.Level; // Import for setting log levels
import java.util.logging.Logger; // Import for logging messages and exceptions
import javax.swing.ImageIcon; // Import for handling image icons
import javax.swing.JOptionPane; // Import for showing dialog boxes
import javax.swing.JTable; // Import for handling tables in GUI
import javax.swing.table.DefaultTableModel; // Import for handling table models
import swing.scrollbar.ScrollBarCustom; // Import for custom scroll bars
import static view.TenantScreen.tenantSelected; // Import static tenantSelected from TenantScreen

/**
 *
 * @author Liron
 */
public class PropertyScreen extends javax.swing.JFrame {
public static Property propertySelected;
 public static Tenant TenantSelected;
    /**
     * Creates new form NewJFrame1
     */
    public PropertyScreen() {
        initComponents();
         // Initialize the ExpenseManager and add data to the table.
        PropertyManager pm = new PropertyManager();
        pm.addDataToTable((DefaultTableModel) tblProperties.getModel());
         jScrollPane1.setVerticalScrollBar(new ScrollBarCustom());
        tblProperties.setShowGrid(true);
        tblProperties.setSelectionBackground(Color.decode("#2AC2EC"));
        
           // Adding search options and setting the default option to "propertyID"
        textFieldSearchOption.addOption(new SearchOption("PropertyID", new ImageIcon(getClass().getResource("/icon/user (2).png"))));
        textFieldSearchOption.addOption(new SearchOption("Adress", new ImageIcon(getClass().getResource("/icon/4.png"))));
        textFieldSearchOption.addOption(new SearchOption("Suburb", new ImageIcon(getClass().getResource("/icon/5.png"))));
        textFieldSearchOption.addOption(new SearchOption("Category", new ImageIcon(getClass().getResource("/icon/1.png"))));
        textFieldSearchOption.addOption(new SearchOption("Bedrooms", new ImageIcon(getClass().getResource("/icon/6.png"))));
        textFieldSearchOption.addOption(new SearchOption("Bathrooms", new ImageIcon(getClass().getResource("/icon/7.png"))));
        textFieldSearchOption.setSelectedIndex(0);

        // Adding sorting options to the combo box
        ComboBoxSort.addItem("None");
        ComboBoxSort.addItem("Complex (A to Z)");
        ComboBoxSort.addItem("Complex (Z to A)");
        ComboBoxSort.addItem("Bedrooms (Low to High)");
        ComboBoxSort.addItem("Bedrooms (High to Low)");
        ComboBoxSort.addItem("Rent (Low to High)");
        ComboBoxSort.addItem("Rent (High to Low)");

        // Adding action listener to sort the table based on the selected option
        ComboBoxSort.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String selectedOption = ComboBoxSort.getSelectedItem().toString();
                PropertyManager pm = new PropertyManager();
                pm.sortTable(tblProperties, selectedOption);
            }
        });

        // Adding event listener for the search option combo box to update hint text
        textFieldSearchOption.addEventOptionSelected(new SearchOptionEvent() {
            @Override
            public void optionSelected(SearchOption option, int index) {
                textFieldSearchOption.setHint(" Search by " + option.getName() + "...");
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panMain = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProperties = new javax.swing.JTable();
        lblHeading = new javax.swing.JLabel();
        btnBack = new swing.CustomButtonGradient();
        ComboBoxSort = new swing.Combobox();
        textFieldSearchOption = new filter.TextFieldSearchOption();
        btnAddProperty = new swing.CustomButtonGradient();
        btnDeleteProperty = new swing.CustomButtonGradient();
        btnEditProperty = new swing.CustomButtonGradient();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        twitterbtn = new javax.swing.JButton();
        jLabel_inven1 = new javax.swing.JLabel();
        fbookbtn = new javax.swing.JButton();
        instagrambtn = new javax.swing.JButton();
        Mailbtn = new javax.swing.JButton();
        ytubebtn = new javax.swing.JButton();
        jLabel_inven2 = new javax.swing.JLabel();
        btnprinttab = new swing.CustomButtonGradient();
        btnViewAparmentCategory = new swing.CustomButtonGradient();
        btnViewProperty1 = new swing.CustomButtonGradient();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(21, 25, 28));

        panMain.setBackground(new java.awt.Color(21, 25, 28));

        tblProperties.setBackground(new java.awt.Color(24, 25, 26));
        tblProperties.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        tblProperties.setForeground(new java.awt.Color(169, 224, 49));
        tblProperties.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "#", "Complex", "UnitNo", "Adress", "Suburb", "Category", "Bedrooms", "Bathroom", "Occupied", "Rent", "Image"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProperties.setGridColor(new java.awt.Color(0, 255, 102));
        tblProperties.setRowHeight(25);
        tblProperties.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblProperties);
        if (tblProperties.getColumnModel().getColumnCount() > 0) {
            tblProperties.getColumnModel().getColumn(0).setMinWidth(40);
            tblProperties.getColumnModel().getColumn(0).setPreferredWidth(40);
            tblProperties.getColumnModel().getColumn(0).setMaxWidth(40);
            tblProperties.getColumnModel().getColumn(2).setMinWidth(60);
            tblProperties.getColumnModel().getColumn(2).setPreferredWidth(60);
            tblProperties.getColumnModel().getColumn(2).setMaxWidth(60);
            tblProperties.getColumnModel().getColumn(4).setMinWidth(100);
            tblProperties.getColumnModel().getColumn(4).setPreferredWidth(100);
            tblProperties.getColumnModel().getColumn(4).setMaxWidth(100);
            tblProperties.getColumnModel().getColumn(5).setMinWidth(100);
            tblProperties.getColumnModel().getColumn(5).setPreferredWidth(100);
            tblProperties.getColumnModel().getColumn(5).setMaxWidth(100);
            tblProperties.getColumnModel().getColumn(6).setMinWidth(80);
            tblProperties.getColumnModel().getColumn(6).setPreferredWidth(80);
            tblProperties.getColumnModel().getColumn(6).setMaxWidth(80);
            tblProperties.getColumnModel().getColumn(7).setMinWidth(80);
            tblProperties.getColumnModel().getColumn(7).setPreferredWidth(80);
            tblProperties.getColumnModel().getColumn(7).setMaxWidth(80);
            tblProperties.getColumnModel().getColumn(8).setMinWidth(40);
            tblProperties.getColumnModel().getColumn(8).setPreferredWidth(40);
            tblProperties.getColumnModel().getColumn(8).setMaxWidth(40);
            tblProperties.getColumnModel().getColumn(9).setMinWidth(60);
            tblProperties.getColumnModel().getColumn(9).setPreferredWidth(60);
            tblProperties.getColumnModel().getColumn(9).setMaxWidth(60);
        }

        lblHeading.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lblHeading.setForeground(new java.awt.Color(169, 224, 49));
        lblHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeading.setText("Apartment TABLE");

        btnBack.setForeground(new java.awt.Color(0, 0, 0));
        btnBack.setText("Back");
        btnBack.setColor1(new java.awt.Color(15, 214, 79));
        btnBack.setColor2(new java.awt.Color(248, 239, 66));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        ComboBoxSort.setBackground(new java.awt.Color(36, 37, 38));
        ComboBoxSort.setForeground(new java.awt.Color(169, 224, 49));
        ComboBoxSort.setLabeText("Sort");

        textFieldSearchOption.setBackground(new java.awt.Color(36, 37, 38));
        textFieldSearchOption.setForeground(new java.awt.Color(169, 224, 49));
        textFieldSearchOption.setColorOverlay1(new java.awt.Color(15, 214, 79));
        textFieldSearchOption.setColorOverlay2(new java.awt.Color(248, 239, 66));
        textFieldSearchOption.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFieldSearchOptionKeyReleased(evt);
            }
        });

        btnAddProperty.setForeground(new java.awt.Color(0, 0, 0));
        btnAddProperty.setText("Add Apartment");
        btnAddProperty.setColor1(new java.awt.Color(169, 224, 49));
        btnAddProperty.setColor2(new java.awt.Color(169, 224, 49));
        btnAddProperty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPropertyActionPerformed(evt);
            }
        });

        btnDeleteProperty.setForeground(new java.awt.Color(0, 0, 0));
        btnDeleteProperty.setText("Delete Apartment");
        btnDeleteProperty.setColor1(new java.awt.Color(169, 224, 49));
        btnDeleteProperty.setColor2(new java.awt.Color(169, 224, 49));
        btnDeleteProperty.setMaximumSize(new java.awt.Dimension(100, 36));
        btnDeleteProperty.setMinimumSize(new java.awt.Dimension(100, 36));
        btnDeleteProperty.setPreferredSize(new java.awt.Dimension(100, 36));
        btnDeleteProperty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePropertyActionPerformed(evt);
            }
        });

        btnEditProperty.setForeground(new java.awt.Color(0, 0, 0));
        btnEditProperty.setText("Edit Apartment");
        btnEditProperty.setColor1(new java.awt.Color(169, 224, 49));
        btnEditProperty.setColor2(new java.awt.Color(169, 224, 49));
        btnEditProperty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPropertyActionPerformed(evt);
            }
        });

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_32px.png"))); // NOI18N
        jButton10.setToolTipText("Close");
        jButton10.setBorder(null);
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setRequestFocusEnabled(false);
        jButton10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Cancel_30px_3.png"))); // NOI18N
        jButton10.setVerifyInputWhenFocusTarget(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Minus_32px_1.png"))); // NOI18N
        jButton11.setToolTipText("Minimize");
        jButton11.setBorder(null);
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setFocusPainted(false);
        jButton11.setRequestFocusEnabled(false);
        jButton11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Minus_30px_3.png"))); // NOI18N
        jButton11.setVerifyInputWhenFocusTarget(false);
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        twitterbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Twitter_32px.png"))); // NOI18N
        twitterbtn.setToolTipText("Twitter");
        twitterbtn.setBorder(null);
        twitterbtn.setBorderPainted(false);
        twitterbtn.setContentAreaFilled(false);
        twitterbtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Twitter_32px_2.png"))); // NOI18N
        twitterbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twitterbtnActionPerformed(evt);
            }
        });

        jLabel_inven1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel_inven1.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven1.setText("Connect with us on     ");

        fbookbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Facebook_32px_2.png"))); // NOI18N
        fbookbtn.setToolTipText("Facebook");
        fbookbtn.setBorder(null);
        fbookbtn.setBorderPainted(false);
        fbookbtn.setContentAreaFilled(false);
        fbookbtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Facebook_32px_7.png"))); // NOI18N
        fbookbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fbookbtnActionPerformed(evt);
            }
        });

        instagrambtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Instagram_32px.png"))); // NOI18N
        instagrambtn.setToolTipText("Instagram");
        instagrambtn.setBorder(null);
        instagrambtn.setBorderPainted(false);
        instagrambtn.setContentAreaFilled(false);
        instagrambtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Instagram_32px_3.png"))); // NOI18N
        instagrambtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instagrambtnActionPerformed(evt);
            }
        });

        Mailbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Secured_Letter_32px.png"))); // NOI18N
        Mailbtn.setToolTipText("Email");
        Mailbtn.setBorder(null);
        Mailbtn.setBorderPainted(false);
        Mailbtn.setContentAreaFilled(false);
        Mailbtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Secured_Letter_32px_2.png"))); // NOI18N
        Mailbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MailbtnActionPerformed(evt);
            }
        });

        ytubebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_YouTube_32px.png"))); // NOI18N
        ytubebtn.setToolTipText("YouTube");
        ytubebtn.setBorder(null);
        ytubebtn.setBorderPainted(false);
        ytubebtn.setContentAreaFilled(false);
        ytubebtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_YouTube_32px_1.png"))); // NOI18N
        ytubebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ytubebtnActionPerformed(evt);
            }
        });

        jLabel_inven2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel_inven2.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven2.setText("support         Help");

        btnprinttab.setForeground(new java.awt.Color(0, 0, 0));
        btnprinttab.setText("print table");
        btnprinttab.setColor1(new java.awt.Color(169, 224, 49));
        btnprinttab.setColor2(new java.awt.Color(169, 224, 49));
        btnprinttab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprinttabActionPerformed(evt);
            }
        });

        btnViewAparmentCategory.setForeground(new java.awt.Color(0, 0, 0));
        btnViewAparmentCategory.setText("Add Apartment category");
        btnViewAparmentCategory.setColor1(new java.awt.Color(169, 224, 48));
        btnViewAparmentCategory.setColor2(new java.awt.Color(169, 224, 49));
        btnViewAparmentCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAparmentCategoryActionPerformed(evt);
            }
        });

        btnViewProperty1.setForeground(new java.awt.Color(0, 0, 0));
        btnViewProperty1.setText("View Apartment");
        btnViewProperty1.setColor1(new java.awt.Color(169, 224, 48));
        btnViewProperty1.setColor2(new java.awt.Color(169, 224, 49));
        btnViewProperty1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProperty1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panMainLayout = new javax.swing.GroupLayout(panMain);
        panMain.setLayout(panMainLayout);
        panMainLayout.setHorizontalGroup(
            panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panMainLayout.createSequentialGroup()
                .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panMainLayout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panMainLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panMainLayout.createSequentialGroup()
                                .addComponent(textFieldSearchOption, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ComboBoxSort, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82))
                            .addGroup(panMainLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panMainLayout.createSequentialGroup()
                                        .addComponent(twitterbtn)
                                        .addGap(6, 6, 6)
                                        .addComponent(fbookbtn)
                                        .addGap(6, 6, 6)
                                        .addComponent(instagrambtn))
                                    .addComponent(jLabel_inven1))
                                .addGap(109, 109, 109)
                                .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(108, 108, 108)
                                .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panMainLayout.createSequentialGroup()
                                        .addComponent(Mailbtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ytubebtn))
                                    .addComponent(jLabel_inven2))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(panMainLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 937, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panMainLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnViewAparmentCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddProperty, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteProperty, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditProperty, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnprinttab, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewProperty1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );
        panMainLayout.setVerticalGroup(
            panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panMainLayout.createSequentialGroup()
                .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panMainLayout.createSequentialGroup()
                                .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panMainLayout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addComponent(fbookbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(twitterbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(instagrambtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_inven1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panMainLayout.createSequentialGroup()
                                .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ytubebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Mailbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_inven2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 45, Short.MAX_VALUE)
                .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxSort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldSearchOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnprinttab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditProperty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteProperty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddProperty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewProperty1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewAparmentCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // Open the HomeScreen and close the current ExpenseScreen.
        // new HomeScreen().setVisible(true);
        new HomeScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void textFieldSearchOptionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldSearchOptionKeyReleased
         // Check if the search option is selected
        if (textFieldSearchOption.isSelected()) {
            // Get the index of the selected search option
            int option = textFieldSearchOption.getSelectedIndex();

            // Get the text entered in the search field and add '%' to enable partial matching
            String text = "%" + textFieldSearchOption.getText().trim() + "%";

            // Create a new PropertyManager to handle the search operation
            PropertyManager pm = new PropertyManager();

            // Use a switch statement to perform the search based on the selected option
            switch (option) {
                case 0:
                    // Search for properties where PropertyID matches the entered text
                    pm.addSearchedDataToTable((DefaultTableModel) tblProperties.getModel(), "WHERE PropertyID LIKE ?", text);
                    break;
                case 1:
                    // Search for properties where Address matches the entered text
                    pm.addSearchedDataToTable((DefaultTableModel) tblProperties.getModel(), "WHERE Address LIKE ?", text);
                    break;
                case 2:
                    // Search for properties where Suburb matches the entered text
                    pm.addSearchedDataToTable((DefaultTableModel) tblProperties.getModel(), "WHERE Suburb LIKE ?", text);
                    break;
                case 3:
                    // Search for properties where PropertyType matches the entered text
                    pm.addSearchedDataToTable((DefaultTableModel) tblProperties.getModel(), "WHERE Category LIKE ?", text);
                    break;
                case 4:
                    // Search for properties where Bedrooms matches the entered text
                    pm.addSearchedDataToTable((DefaultTableModel) tblProperties.getModel(), "WHERE Bedrooms LIKE ?", text);
                    break;
                case 5:
                    // Search for properties where Bathrooms matches the entered text
                    pm.addSearchedDataToTable((DefaultTableModel) tblProperties.getModel(), "WHERE Bathrooms LIKE ?", text);
                    break;
                default:
                    // If no option is selected, do nothing
                    break;
            }
        }
    }//GEN-LAST:event_textFieldSearchOptionKeyReleased

    private void btnAddPropertyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPropertyActionPerformed
        // Open the AddExpenseScreen and close the current ExpenseScreen.
        new AddPropertyScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddPropertyActionPerformed

    private void btnDeletePropertyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePropertyActionPerformed
     // Get the row number of the selected property from the table
        int rowSelected = tblProperties.getSelectedRow();

        // Check if a row is selected in the table
        if (rowSelected == -1) {
            // If no row is selected, show an error message to the user
            JOptionPane.showMessageDialog(null, "Please select a property to delete");
        } else {
            // If a row is selected, get the property ID of the selected property
            int propertyID = (int) tblProperties.getValueAt(rowSelected, 0);

            // Show a confirmation dialog to the user to confirm the deletion
            int confirmation = JOptionPane.showConfirmDialog(PropertyScreen.this, "Are you sure you want to delete this property?", "Deletion Confirmation", JOptionPane.YES_NO_OPTION);

            // If the user confirms the deletion
            if (confirmation == JOptionPane.YES_OPTION) {
                // Delete the property using the PropertyManager
                PropertyManager pm = new PropertyManager();
                pm.deleteProperty(propertyID);

                // Update the table to reflect the changes
                pm.addSearchedDataToTable((DefaultTableModel) tblProperties.getModel(), "");

                // Show a success message to the user
                JOptionPane.showMessageDialog(null, "Property has been deleted");
            }
        }
    }//GEN-LAST:event_btnDeletePropertyActionPerformed

    private void btnEditPropertyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPropertyActionPerformed
      // Get the row number of the selected property from the table
        int rowSelected = tblProperties.getSelectedRow();

        // Check if a row is selected in the table
        if (rowSelected == -1) {
            // If no row is selected, show an error message to the user
            JOptionPane.showMessageDialog(null, "Please select a property to edit");
        } else {
           // If a row is selected, retrieve the data from the selected row
int propertyID = (int) tblProperties.getValueAt(rowSelected, 0);
String complex = (String) tblProperties.getValueAt(rowSelected, 1);
String UnitNo = (String) tblProperties.getValueAt(rowSelected, 2);
String address = (String) tblProperties.getValueAt(rowSelected, 3);
String suburb = (String) tblProperties.getValueAt(rowSelected, 4);
String category = (String) tblProperties.getValueAt(rowSelected, 5);
int bedrooms = (int) tblProperties.getValueAt(rowSelected, 6);
double bathrooms = (double) tblProperties.getValueAt(rowSelected, 7);
boolean occupied = (boolean) tblProperties.getValueAt(rowSelected, 8);
int rent = (int) tblProperties.getValueAt(rowSelected, 9);
String image = (String) tblProperties.getValueAt(rowSelected, 10);


            // Create a new Property object with the retrieved data
  propertySelected = new Property(propertyID,suburb ,complex, UnitNo ,address,  category, bedrooms, bathrooms, occupied, rent, image);

            // Open the EditPropertyScreen to allow the user to edit the property details
            new EditPropertyScreen().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnEditPropertyActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

    }//GEN-LAST:event_jButton11ActionPerformed

    private void twitterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twitterbtnActionPerformed
        try {
            // Specify the URL
            String url = "https://x.com/";
            // Use Desktop class to open the URL
            if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)) {
                Desktop.getDesktop().browse(new URI(url));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_twitterbtnActionPerformed

    private void fbookbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fbookbtnActionPerformed
        try {
            // Specify the URL
            String url = "https://www.facebook.com/liron.mindel.3";
            // Use Desktop class to open the URL
            if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)) {
                Desktop.getDesktop().browse(new URI(url));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_fbookbtnActionPerformed

    private void instagrambtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instagrambtnActionPerformed
        try {
            // Specify the URL
            String url = "https://instagram.com/";
            // Use Desktop class to open the URL
            if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)) {
                Desktop.getDesktop().browse(new URI(url));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_instagrambtnActionPerformed

    private void MailbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MailbtnActionPerformed

        Desktop desktop;
        if (Desktop.isDesktopSupported()
            && (desktop = Desktop.getDesktop()).isSupported(Desktop.Action.MAIL)) {
            try {
                URI mailto = new URI("mailto:your-email@example.com?subject=Apartment%20rental%20manemgment%20support:");
                desktop.mail(mailto);
            } catch (URISyntaxException ex) {
                Logger.getLogger(SplashScreen.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(SplashScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            // TODO fallback to some Runtime.exec(..) voodoo?
            throw new RuntimeException("desktop doesn't support mailto; mail is dead anyway ;)");
        }
    }//GEN-LAST:event_MailbtnActionPerformed

    private void ytubebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ytubebtnActionPerformed
        try {
            String url = "https://vimeo.com/994576038#t=7m50s.";
            // Use Desktop class to open the URL
            if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)) {
                Desktop.getDesktop().browse(new URI(url));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_ytubebtnActionPerformed

    private void btnprinttabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprinttabActionPerformed
        /*    try {
            tblExpenses.print(JTable.PrintMode.FIT_WIDTH);
        } catch (Exception e) {
            e.printStackTrace();
        }*/
        PrinterJob printerJob = PrinterJob.getPrinterJob();
        printerJob.setPrintable(tblProperties.getPrintable(JTable.PrintMode.FIT_WIDTH, null, null));

        // Create a PageFormat with landscape orientation and A4 paper size
        PageFormat pageFormat = printerJob.defaultPage();
        Paper paper = pageFormat.getPaper();

        // A4 paper dimensions in inches
        double width = 8.27 * 72; // A4 width in points (1 inch = 72 points)
        double height = 11.69 * 72; // A4 height in points

        // Set the paper size
        paper.setSize(width, height);
        paper.setImageableArea(0, 0, width, height);

        // Apply paper to PageFormat and set orientation to landscape
        pageFormat.setPaper(paper);
        pageFormat.setOrientation(PageFormat.LANDSCAPE);

        printerJob.setPrintable(tblProperties.getPrintable(JTable.PrintMode.FIT_WIDTH, null, null), pageFormat);

        boolean doPrint = printerJob.printDialog();
        if (doPrint) {
            try {
                printerJob.print();
            } catch (PrinterException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnprinttabActionPerformed

    private void btnViewAparmentCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAparmentCategoryActionPerformed
        
        new CategoryScreen().setVisible(true);
this.dispose();
        
    }//GEN-LAST:event_btnViewAparmentCategoryActionPerformed

    private void btnViewProperty1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProperty1ActionPerformed
        // TODO add your handling code here:
        // Get the row number of the selected property from the table
        int rowSelected = tblProperties.getSelectedRow();

        // Check if a property is selected in the table.
        if (rowSelected == -1) {
            JOptionPane.showMessageDialog(null, "Please select a property to view");
        } else {
            // Retrieve property details from the selected row in the table.
            int propertyID = (int) tblProperties.getValueAt(rowSelected, 0);
            String suburb = (String) tblProperties.getValueAt(rowSelected, 1);
            String complex = (String) tblProperties.getValueAt(rowSelected, 2);
            String UnitNo = (String) tblProperties.getValueAt(rowSelected, 3);
            String adress = (String) tblProperties.getValueAt(rowSelected, 4);
            String category = (String) tblProperties.getValueAt(rowSelected, 5);
            int bedrooms = (int) tblProperties.getValueAt(rowSelected, 6);
            double bathrooms = (double) tblProperties.getValueAt(rowSelected, 7);
            boolean occupied = (boolean) tblProperties.getValueAt(rowSelected, 8);
            int rent = (int) tblProperties.getValueAt(rowSelected, 9);
            String image = (String) tblProperties.getValueAt(rowSelected, 10);

            // Create a Property instance with the selected property details.
            propertySelected = new Property(propertyID,suburb,complex, UnitNo,adress,category,bedrooms, bathrooms, occupied, rent , image);

            // Get the owner details for the selected property.
            TenantManager Tm = new  TenantManager();
            tenantSelected = Tm.getTenant(propertyID);

            // Open the ViewPropertyScreen and pass the property and owner details.
            new ViewPropertyScreen(propertySelected, tenantSelected, false, false).setVisible(true);
           this.dispose();
        }
    }//GEN-LAST:event_btnViewProperty1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PropertyScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PropertyScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PropertyScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PropertyScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PropertyScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Combobox ComboBoxSort;
    private javax.swing.JButton Mailbtn;
    private swing.CustomButtonGradient btnAddProperty;
    private swing.CustomButtonGradient btnBack;
    private swing.CustomButtonGradient btnDeleteProperty;
    private swing.CustomButtonGradient btnEditProperty;
    private swing.CustomButtonGradient btnViewAparmentCategory;
    private swing.CustomButtonGradient btnViewProperty1;
    private swing.CustomButtonGradient btnprinttab;
    private javax.swing.JButton fbookbtn;
    private javax.swing.JButton instagrambtn;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel_inven1;
    private javax.swing.JLabel jLabel_inven2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JPanel panMain;
    private javax.swing.JTable tblProperties;
    private filter.TextFieldSearchOption textFieldSearchOption;
    private javax.swing.JButton twitterbtn;
    private javax.swing.JButton ytubebtn;
    // End of variables declaration//GEN-END:variables
}
